### PR TITLE
Feature likelihood components

### PR DESCRIPTION
**Pull request by colinpmillar**
Add the values for negative log likelihood for the components:
1. catch
2. survey 1
3. survey 2
4.  ...
5. SR relationship if present

to the fitSumm component of the a4aFit object

### CODE REVIEW

**Comment by iagomosqueira** [comment]
We need a new Linux executable too if the .tpl file has changed

**Comment by colinpmillar** [comment]
Yes - I can't build these easily these days, is this something you guys can
do?

**Comment by iagomosqueira** [comment]
Yes we can!
  
  
  
  
 --- Sent from a mobile  

  
  
  
  
  
>

**Comment by ejardim** [comment]
Why having the likelihood components named comp1, comp2 etc instead of human readable names, like sr, catch, etc

**Pull request merged**
